spring.datasource.url=jdbc:mysql://localhost:3306/ms-pedido-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Neymar22#
eureka.instance.prefer-ip-address=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Disjuntor - Circuit Breaker
resilience4j.circuitbreaker.instances.verificaAutorizacao.slidingWindowSize=3
resilience4j.circuitbreaker.instances.verificaAutorizacao.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.verificaAutorizacao.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.verificaAutorizacao.waitDurationInOpenState= 10s


spring.rabbitmq.addresses=amqps://wpvodbkp:Gp8GBmQXyARiGApnjhq5M02rFoPyvaMu@jackal.rmq.cloudamqp.com/wpvodbkp
