server.port=0

spring.datasource.url=jdbc:mysql://localhost:3306/ms-usuario-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Neymar22#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false

spring.rabbitmq.addresses=amqps://wpvodbkp:Gp8GBmQXyARiGApnjhq5M02rFoPyvaMu@jackal.rmq.cloudamqp.com/wpvodbkp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucasserrano376@gmail.com
spring.mail.password=hgcc skbz gpsg cyye
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
eureka.instance.prefer-ip-address=true
